[build]
  # This will be run the site build
  command = "env && npm install && npm run build"
  # serve all files in this directory statically
  publish = "dist/frontend"
  # functions build directory
  functions = "dist/functions"
